application-insights/ServiceFabricCluster.json, application-insights/WindowsVirtualMachine.json, application-insights/WindowsVirtualMachineScaleSet.json
=> Update Windows Azure Diagnostics examples for AppInsights

azure-firewall/AzureFirewall.omsview
Used in the https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/firewall/log-analytics-samples.md article
=> Added AzureFirewall.omsview

azure-resource-manager/emptyRG.json
Fixes #57
I have included an example of how I'm planning to use this template.
- https://github.com/pckls/azure-resource-manager-templates/tree/master/resource-group-creation
=> Adding tags parameter and passing through to resource group

event-grid/EventHubsDataMigration.json
I could reproduce the issue: https://github.com/MicrosoftDocs/azure-docs/issues/37652. 
Fixed it by updating the JSON.
=> updated the data ware house section.

get-started-with-templates/add-name/azuredeploy.json, get-started-with-templates/add-sku/azuredeploy.json, get-started-with-templates/add-storage/azuredeploy.json, get-started-with-templates/quickstart-template/azuredeploy.json
- East US -> eastus
- update the quickstart template to match the newly updated quickstart template.
=> update the quickstart template

deployment-script/deploymentscript-basic-cli.json, deployment-script/deploymentscript-basic.json, deployment-script/deploymentscript-helloworld-primaryscripturi.json, deployment-script/deploymentscript-helloworld.json, deployment-script/deploymentscript-jsonEscape.json, deployment-script/deploymentscript-keyvault-mi.json, deployment-script/deploymentscript-keyvault-subscription.json, deployment-script/deploymentscript-keyvault.json, deployment-script/deploymentscript-status.json
Reverts Azure/azure-docs-json-samples#188
=> Revert "update the retention interval to 25 hours"

mslearn-arm-deploymentscripts-sample/appsettings.Staging.json, mslearn-arm-deploymentscripts-sample/appsettings.json, mslearn-arm-deploymentscripts-sample/swagger.Staging.json
These are some json files that are copied to a storage account as part of the exercises in a Learn module on deployment scripts in ARM templates.
=> Data files for the Microsoft Learn module on ARM template deployment scripts.

linked-template-relpath/children/grandchildren/nestedGrandchild.json, linked-template-relpath/children/nestedChild.json, linked-template-relpath/linkedTemplate.json, linked-template-relpath/mainTemplate.json, linked-template-relpath/state-and-deploy.ps1
Will be removed after the testing.
=> test the linked template relative path scenario

azure-resource-manager/multipleinstance/loopvariables.bicep, azure-resource-manager/multipleinstance/multiplesecurityrules.bicep
Adds Bicep examples for loops in variables.
=> Adds Bicep examples for loops in variables

azure-resource-manager/multipleinstance/copystorage.json, azure-resource-manager/multipleinstance/copystoragewitharray.json, azure-resource-manager/multipleinstance/copyvariables.json, azure-resource-manager/multipleinstance/loopserialstorage.bicep, azure-resource-manager/multipleinstance/loopstorage.bicep, azure-resource-manager/multipleinstance/loopstoragewitharray.bicep, azure-resource-manager/multipleinstance/multiplesecurityrules.bicep, azure-resource-manager/multipleinstance/multiplesecurityrules.json, azure-resource-manager/multipleinstance/multiplesecurityrules.parameters.json, azure-resource-manager/multipleinstance/serialcopystorage.json
- Adds three Bicep examples to create storage accounts.
- Updates Bicep symbolic names to camelCase and adds parameter for location.
- Updates schema, API version, parameters, and indentation for JSON files.
=> Adds Bicep examples for storage accounts

azure-resource-manager/variablesconfigurations.bicep
Adds `@allowed` decorator for `param` allowed values.
=> Adds parameter decorator

azure-resource-manager/functions/array/concat-array.json, azure-resource-manager/functions/array/contains.json, azure-resource-manager/functions/array/empty.json, azure-resource-manager/functions/array/first.json, azure-resource-manager/functions/array/intersection.json, azure-resource-manager/functions/array/last.json, azure-resource-manager/functions/array/length.json, azure-resource-manager/functions/array/skip.json, azure-resource-manager/functions/array/take.json, azure-resource-manager/functions/array/union.json, azure-resource-manager/functions/numeric/max.json, azure-resource-manager/functions/numeric/min.json, azure-resource-manager/functions/string/concat-string.json
- Updates function templates used in [template-functions-array](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-array) article.
- Fixes indentation and schema version.
=> Updates array templates

azure-resource-manager/functions/comparison/coalesce.json, azure-resource-manager/functions/comparison/equals.json, azure-resource-manager/functions/comparison/greater.json, azure-resource-manager/functions/comparison/greaterorequals.json, azure-resource-manager/functions/comparison/less.json, azure-resource-manager/functions/comparison/lessorequals.json, azure-resource-manager/functions/date/dateTimeAdd.json, azure-resource-manager/functions/date/dateTimeAddAutomation.json, azure-resource-manager/functions/date/utcNowTag.json, azure-resource-manager/functions/deployment/deployment.json, azure-resource-manager/functions/deployment/deploymentsubscription.json, azure-resource-manager/functions/deployment/parameters.json, azure-resource-manager/functions/deployment/variables.json
- Updates JSON samples for comparison, date, and deployment.
- Fixes indentation and schema version.
=> Updates sample templates

azure-resource-manager/functions/string/base64.json, azure-resource-manager/functions/string/datauri.json, azure-resource-manager/functions/string/format.json, azure-resource-manager/functions/string/guid.json, azure-resource-manager/functions/string/indexof.json, azure-resource-manager/functions/string/newguid-storageaccount.json, azure-resource-manager/functions/string/newguid.json, azure-resource-manager/functions/string/replace.json, azure-resource-manager/functions/string/split.json, azure-resource-manager/functions/string/startsendswith.json, azure-resource-manager/functions/string/string.json, azure-resource-manager/functions/string/substring.json, azure-resource-manager/functions/string/tolower.json, azure-resource-manager/functions/string/trim.json, azure-resource-manager/functions/string/uniquestring.json, azure-resource-manager/functions/string/uri.json
- Updates and adds JSON samples for string functions.
- Adds new samples.
- Fixes indentation and schema version.
=> Updates string sample templates

azure-resource-manager/linkedtemplates/helloworld.json, azure-resource-manager/linkedtemplates/helloworldparent.json, azure-resource-manager/linkedtemplates/linked-dependency.json, azure-resource-manager/linkedtemplates/public-ip-parentloadbalancer.json, azure-resource-manager/linkedtemplates/public-ip.json, azure-resource-manager/linkedtemplates/static-public-ip-parent.json, azure-resource-manager/linkedtemplates/static-public-ip.json
- Updates samples in `/azure-resource-manager/linkedtemplates`.
- API version
- Indentation
=> Updates linked template samples

azure-resource-manager/crossresourcegroupproperties.json, azure-resource-manager/crosssubscription.json, azure-resource-manager/resourcegroupname.json, azure-resource-manager/scope/default-mg.json, azure-resource-manager/scope/default-rg.json, azure-resource-manager/scope/default-sub.json, azure-resource-manager/scope/default-tenant.json, azure-resource-manager/scope/different-sub-to-resource-group.json, azure-resource-manager/scope/locktargetscope.json, azure-resource-manager/scope/management-group-create-mg.json, azure-resource-manager/scope/management-group-to-tenant.json, azure-resource-manager/scope/mg-to-resource-group.json, azure-resource-manager/scope/mg-to-subscription.json, azure-resource-manager/scope/resource-group-create-mg.json, azure-resource-manager/scope/resource-group-to-subscription.json, azure-resource-manager/scope/resource-group-to-tenant.json, azure-resource-manager/scope/roletargetscope.json, azure-resource-manager/scope/same-sub-to-resource-group.json, azure-resource-manager/scope/scope-mg.json, azure-resource-manager/scope/storageandrole.json, azure-resource-manager/scope/sub-to-resource-group.json, azure-resource-manager/scope/sub-to-sub.json, azure-resource-manager/scope/subscription-create-mg.json, azure-resource-manager/scope/subscription-to-tenant.json, azure-resource-manager/scope/tenant-to-mg.json, azure-resource-manager/scope/tenant-to-rg.json, azure-resource-manager/scope/tenant-to-subscription.json
- Updates schema version, API version, and indentation.
- Adds file for a linked template.
=> Updates scope samples

azure-resource-manager/what-if/readme.md, deployment-script/readme.md, deployment-script/readme.txt, get-started-deployment/linked-template/azuredeploy.json, get-started-deployment/linked-template/linkedStorageAccount.json, get-started-deployment/local-template/azuredeploy.json, get-started-deployment/readme.md
- Updates API versions.
- Updates _readme.md_ files.
- Replaces _readme.txt_ with _readme.md_.
=> Updates deployment samples

mslearn-arm-Module-sample/identity.json, mslearn-arm-Module-sample/storage.json, mslearn-arm-deploymentscripts-sample/swagger.Staging.json
- Updates API version, fixes indentation, reorders `resources` properties.
=> Updates mslearn sample templates

application-insights/ServiceFabricCluster.json, application-insights/WindowsVirtualMachine.json, application-insights/WindowsVirtualMachineScaleSet.json, application-insights/readme.md
Updates sample templates in _application-insights_ directory.
- Updates schema and API versions.
- Reorders properties for `parameters` and `resources`.
- Fixes indentation
- Adds readme.md file with links to docs that use these templates.
@cweining I'm working on a project for the JSON samples repository and updated templates that are linked from documents that show you as the author.
=> Updates application insights samples

container-instances/aci-deploy-volume-emptydir.json, container-instances/aci-deploy-volume-gitrepo.json, container-instances/aci-deploy-volume-secret.json, container-instances/readme.md
Updates sample templates in _container-instances_ directory.
- Updates schema and API versions.
- Reorders properties for `resources`.
- Adds readme.md file with links to docs that use these templates.
@macolso I'm working on a project for the JSON samples repository and updated templates that are linked from documents that show you as the author. 
=> Updates container instances samples

event-grid/EventHubsDataMigration.json, event-grid/readme.md
- Fixes parameter descriptions for `sqlServerName` and `sqlServerUserName` because the descriptions were inverted.
- Reorders properties for `resources`.
- Fixes indentation.
- Adds readme.md with link to article that uses template.
@spelluru I made some minor adjustments in the template.
=> Updates event hub sample

deployment-script/deploymentscript-basic.json, deployment-script/deploymentscript-helloworld-primaryscripturi.json, deployment-script/deploymentscript-helloworld.json, deployment-script/deploymentscript-keyvault-mi.json, deployment-script/deploymentscript-keyvault-subscription.json, deployment-script/deploymentscript-keyvault.json
- Updates API version.
- Fixes indentation. 
cc: @mumian @tfitzmac
=> Updates deployment script samples

custom-providers/customprovider.json
=> Updates API versions
